USE movies_db;
SHOW TABLES;

/*PRIMERA PARTE
SELECT
1.MOSTAR TODOS LOS REGISTROS DE LA TABAL DE MOVIES*/
SELECT * 
FROM movies;

/*2.MOSTRAR EL NOMBRE, APELLIDO Y RAITING DE TODOS LOS ACTORES*/
SELECT first_name,last_name,rating 
FROM actors;

/*3.MOSTRAR EL TITULO DE TODAS LAS SERIES*/
SELECT title 
FROM series;

/*WHERE Y ORDER BY
4. MOSTRAR EL NOMBRE Y APELLIDO DE LOS ACTORES CUYO NOMBRE SEA MAYOR A 7,5*/
SELECT first_name,last_name 
FROM actors 
WHERE rating > 7.5;

/*5. MOSTRAR EL TITULO DE LAS PELICULAS, EL RATING Y LOS PREMIOS DE LAS PELICULAS CON 
UN RATING MAYOR A 7,5 Y CON MAS DE DOS PREMIOS*/

SELECT title,rating,awards  
FROM movies 
WHERE rating > 7.5 AND rating >= 2;

/*6. MOSTRAR EL TITULO DE LAS PELICULAS Y EL RATING ORDENADAS
POR RATING EN FORMA ASCENDENTE*/

SELECT title, rating
FROM movies
ORDER BY rating ASC;

/*BETWEEN Y LIKE
7. MOSTAR EL TITULO Y RATING DE TODAS LAS PELICULAS CUTO TITULO
CUYO TITULO INCLUYA TOY STORY*/

SELECT title, rating
FROM movies
WHERE title LIKE 'Toy Story%';

/*8. MOSTRAR A TODOS LOS ACTORES CUYOS NOMBRES EMPIECEN CON SAM*/

SELECT first_name,last_name
FROM actors
WHERE first_name LIKE 'Sam%';

/*9. MOSTRAR EL TITULO DE LAS PELICULAS QUE SALIERON ENTRE
EL 2004-01-01 Y 2008-12-31*/

SELECT title
FROM movies
WHERE release_date BETWEEN '2004-01-01' AND '2008-12-31';

/*SEGUNDA PARTE
1.QUEREMOS CONOCER EL NOMBE Y GENERO DE TODAS LAS SERIES
EN LA BASE DE DATOS MOVIES*/

SELECT s.title, g.name
FROM series s
INNER JOIN genres g ON s.genre_id = g.id;

/*2. LISTAR LOS TITULOS DE LOS EPISODIOS JUNTO CON EL NOMBRE
APELLIDO DE LOS ACTORES QUE TRABAJAN EN CADA UNA*/

SELECT DISTINCT e.title,a.first_name, a.last_name
FROM episodes e
INNER JOIN actor_episode ae ON e.id = ae.episode_id
INNER JOIN actors a ON ae.actor_id = a.id
INNER JOIN seasons sa ON e.id = e.season_id
INNER JOIN series se ON sa.serie_id = sa.id;


/*3. OBTENER TODOS LOS ACTORES O ACTRICES (MOSTRAR 
NOMBRE Y APELLIDO) QUE SU PELICULA FAVORITA SEA CUALQUIERA
DE LA SAGA DE LA GUERRA DE LAS GALAXIAS*/

SELECT a.first_name, a.last_name, m.title
FROM actors a
INNER JOIN movies m ON a.favorite_movie_id = m.id
WHERE m.title LIKE '%La Guerra de las Galaxias%';

/*4. OBTENER TODOS LOS ACTORES O ACTRICES (NOMBRE Y APELLIDO)
QUE HAN TRABAJADO EN CUALQUIERA DE LAS PELICULAS DE LA SAGA
LAS GUERRAS DE LAS GALAXIAS*/

SELECT a.first_name,a.last_name,m.title
FROM actors a
INNER JOIN actor_movie am ON a.id = am.actor_id
INNER JOIN movies m ON am.movie_id = m.id
WHERE m.title LIKE '%La Guerra de las Galaxias%';

/*5. CREAR UNA LISTA A PARTIR DE LA TABLA DE PELICULAS
MOSTRAR UN REPORTE DE LA CANTIDAD DE PELICULAS POR 
NOMBRE D EGENERO*/

SELECT g.name AS generes_name,COUNT(*) AS number_movies
FROM movies m
INNER JOIN genres g ON m.genre_id = g.id
GROUP BY g.name;


